// business dashboard.
// design system
//  - font
//  - color
//  - icons

// create page login/dasboard/ profile 
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Nova Circle Business Admin',
  description: 'Generated by Nova Circle Business Admin',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
